-- ============================================================================
-- Remediation for stale / duplicate / wrong-timezone lesson data.
--
-- Background: lessons were generated by OLD code on a UTC+2 server, so every
-- wall-clock schedule time was stored ~7h off from the intended America/Bogota
-- time, and repeated generation left duplicate lessons (and one duplicate
-- course_schedule row).
--
-- This script (idempotent, transactional) does, in order:
--   1. add original_start_time column (no-op if present)
--   2. drop duplicate course_schedule rows
--   3. FIX existing lesson times in place -> correct America/Bogota instant
--      (preserves lesson ids, attendance, reports, reschedules, gcal links)
--   4. de-duplicate lessons (never touching an attended/reported row)
--   5. regenerate any MISSING future scheduled lessons over the next 28 days
--
-- Unlike a delete-and-regenerate approach this keeps history intact and only
-- rewrites timestamps, so it is safe to run on untouched prod or on a DB whose
-- future lessons were already deleted.
--
-- School timezone is hardcoded to America/Bogota (matches SCHEDULE_TIMEZONE
-- default). Generation window is 28 days, matching the app generator.
--
-- SAFETY: attendance/class_report FKs are NO ACTION (attended lessons cannot be
-- deleted); lesson_students is ON DELETE CASCADE. Review the verification output
-- at the bottom before COMMIT.
--
-- Assumes at most one schedule slot per (course, day_of_week) — true after
-- step 2. Lessons whose day-of-week matches no current slot keep their old time
-- (orphans from a removed slot); these are reported in verification.
-- ============================================================================

\set TZ '''America/Bogota'''

BEGIN;

-- 1. New column (matches Migration20260603012400).
ALTER TABLE "lesson" ADD COLUMN IF NOT EXISTS "original_start_time" timestamptz(0) NULL;

-- 2. Drop duplicate schedule rows — keep the oldest per (course, day, times).
WITH ranked_schedules AS (
  SELECT id, row_number() OVER (
           PARTITION BY course_id, day_of_week, start_time, end_time
           ORDER BY created_at, id) AS rn
  FROM "course_schedule"
)
DELETE FROM "course_schedule" WHERE id IN (SELECT id FROM ranked_schedules WHERE rn > 1);

-- 3. Fix lesson times in place. The correct instant is the lesson's Bogota
--    calendar date combined with its matching slot's wall-clock time, anchored
--    to America/Bogota. Matched by Bogota day-of-week (0=Sun..6=Sat).
UPDATE "lesson" l
SET start_time = (((l.start_time AT TIME ZONE :TZ)::date + s.start_time::time) AT TIME ZONE :TZ),
    end_time   = (((l.start_time AT TIME ZONE :TZ)::date + s.end_time::time)   AT TIME ZONE :TZ)
FROM "course_schedule" s
WHERE s.course_id = l.course_id
  AND s.day_of_week = extract(dow from (l.start_time AT TIME ZONE :TZ))::int
  AND (
        l.start_time <> (((l.start_time AT TIME ZONE :TZ)::date + s.start_time::time) AT TIME ZONE :TZ)
     OR l.end_time   <> (((l.start_time AT TIME ZONE :TZ)::date + s.end_time::time)   AT TIME ZONE :TZ)
      );

-- 4. De-duplicate lessons sharing (course_id, start_time). Keep the best row
--    (completed > attended/reported > scheduled); delete the rest, but never one
--    carrying attendance or a class report.
WITH ranked_lessons AS (
  SELECT l.id, row_number() OVER (
           PARTITION BY l.course_id, l.start_time
           ORDER BY
             (l.status = 'completed') DESC,
             (EXISTS (SELECT 1 FROM "attendance"   a WHERE a.lesson_id = l.id)) DESC,
             (EXISTS (SELECT 1 FROM "class_report" r WHERE r.lesson_id = l.id)) DESC,
             l.created_at, l.id) AS rn
  FROM "lesson" l
)
DELETE FROM "lesson"
WHERE id IN (SELECT id FROM ranked_lessons WHERE rn > 1)
  AND NOT EXISTS (SELECT 1 FROM "attendance"   a WHERE a.lesson_id = "lesson".id)
  AND NOT EXISTS (SELECT 1 FROM "class_report" r WHERE r.lesson_id = "lesson".id);

-- 5. Regenerate MISSING future scheduled lessons (active courses, next 28 days).
WITH gen AS (
  SELECT c.id AS course_id, c.tutor_id, d::date AS day,
         s.start_time AS st, s.end_time AS et
  FROM "course" c
  JOIN "course_schedule" s ON s.course_id = c.id
  CROSS JOIN generate_series(
    (now() AT TIME ZONE :TZ)::date,
    (now() AT TIME ZONE :TZ)::date + 28,
    interval '1 day') AS d
  WHERE c.is_active
    AND EXISTS (SELECT 1 FROM "course_students" cs WHERE cs.course_id = c.id)
    AND extract(dow from d)::int = s.day_of_week
    AND d::date >= (c.start_date AT TIME ZONE :TZ)::date
),
to_create AS (
  SELECT gen.course_id, gen.tutor_id,
         ((gen.day + gen.st::time) AT TIME ZONE :TZ) AS start_instant,
         ((gen.day + gen.et::time) AT TIME ZONE :TZ) AS end_instant
  FROM gen
  WHERE NOT EXISTS (
    SELECT 1 FROM "lesson" l
    WHERE l.course_id = gen.course_id
      AND l.status <> 'cancelled'
      AND (l.start_time = ((gen.day + gen.st::time) AT TIME ZONE :TZ)
           OR l.original_start_time = ((gen.day + gen.st::time) AT TIME ZONE :TZ))
  )
),
inserted AS (
  INSERT INTO "lesson"
    (id, tutor_id, course_id, start_time, end_time, status,
     created_at, updated_at, reminder_sent, day_before_reminder_sent, confirmation_email_sent)
  SELECT gen_random_uuid(), tutor_id, course_id, start_instant, end_instant, 'scheduled',
         now(), now(), false, false, false
  FROM to_create
  RETURNING id, course_id
)
INSERT INTO "lesson_students" (lesson_id, user_id)
SELECT i.id, cs.user_id
FROM inserted i
JOIN "course_students" cs ON cs.course_id = i.course_id;

-- ---------------------------------------------------------------------------
-- Verification (review before COMMIT)
-- ---------------------------------------------------------------------------
SELECT 'dup_schedule_rows' AS check, count(*)::text AS value
  FROM (SELECT 1 FROM "course_schedule"
        GROUP BY course_id, day_of_week, start_time, end_time HAVING count(*)>1) d
UNION ALL SELECT 'future_scheduled_lessons',
  count(*)::text FROM "lesson" WHERE start_time>now() AND status='scheduled'
UNION ALL SELECT 'lesson_dupe_groups (expect only attended pairs)',
  count(*)::text FROM (SELECT 1 FROM "lesson" GROUP BY course_id,start_time HAVING count(*)>1) d
UNION ALL SELECT 'lessons_not_matching_any_slot (orphans, kept as-is)',
  count(*)::text FROM "lesson" l WHERE NOT EXISTS (
    SELECT 1 FROM "course_schedule" s WHERE s.course_id=l.course_id
      AND s.day_of_week = extract(dow from (l.start_time AT TIME ZONE :TZ))::int);

-- Per-course sanity: distinct Bogota wall-clock times lessons now sit at
SELECT c.title, to_char(l.start_time AT TIME ZONE :TZ,'Dy HH24:MI') AS bogota_time,
       l.status, count(*)
FROM "lesson" l JOIN "course" c ON c.id=l.course_id
GROUP BY c.title, bogota_time, l.status ORDER BY c.title, bogota_time;

-- COMMIT;    -- uncomment to apply
-- ROLLBACK;  -- or roll back if the numbers look wrong
